#!/bin/bash

# Profile Parse

BIFFLE_PATH=/root/biffle-prototype
PROFILE_DIR=/data/profiles

for f in $PROFILE_DIR/*
do
	if [ -f $f ]; then
		python $BIFFLE_PATH/profile-parse.py $f
	fi
done

# Enrich profiles with StackOverflow tags
python $BIFFLE_PATH/utils/SO-tag-download.py

# Enrich profiles with Twitter
python $BIFFLE_PATH/utils/enrich-profiles-with-twitter.py


# Search Generation
WORDCLOUD_PATH=$BIFFLE_PATH/wordclouds

for f in $WORDCLOUD_PATH/*
do
	if [ -f $f ]; then
		python $BIFFLE_PATH/search-terms-mongo.py $f
	fi
done

python $BIFFLE_PATH/search-gen-for-articles.py 


# Search Result Download

#  Download latest serch API results
PHP_FILE_DIR=/var/www/html/search-scripts
DOWNLOAD_DIR=/data/search-results
LOCALHOST_URL=http://50.22.200.186/search-scripts
date=`date +"%m-%d-%Y"`

for file in $( ls $PHP_FILE_DIR ); do
	
	# Skip index.html file
	if [ $file != "index.html" ]; then
		echo "Downloaded $file"
		if [ ! -d "$DOWNLOAD_DIR/$file" ]; then
			mkdir $DOWNLOAD_DIR/$file
		fi
		wget $LOCALHOST_URL/$file -O $DOWNLOAD_DIR/$file/$file-$date
	fi
done

echo "cron-downlad ran at `date`"


# Article Parse
python $BIFFLE_PATH/parse-and-download.py


# Make Recommendations
python $BIFFLE_PATH/make-recommendations.py


# Send Articles
python $BIFFLE_PATH/send-recommendations.py
