#!/bin/bash

curl -XDELETE  'http://localhost:9200/article/text/mapping'

curl -XPUT  'http://localhost:9200/article/text/_mapping?ignore_conflicts=True' -d '
{
    "text": {
      "properties": {
        "date": {
          "type": "date"
        }
      }
    }

}
'
