#!/bin/bash

curl -XGET  'http://localhost:9200/article/text/_search?pretty=true' -d '
{
    "query" : {
      "filtered": {
            "query" : {
              "match_all": {}
            }
      }
    }
}
 '
